'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace corp.ptt.hq_web_s18
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SecurityServiceSoap", [Namespace]:="http://tempuri.org/PTT.Shared.Interface.Service/security")>  _
    Public Class SecurityService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Public ApplicationErrorValue As ApplicationError
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://hq-web-s18.ptt.corp/PTT.Shared.Interface.Service/security.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ApplicationErrorValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Shared.Interface.Service/security/IsAuthenticated", RequestNamespace:="http://tempuri.org/PTT.Shared.Interface.Service/security", ResponseNamespace:="http://tempuri.org/PTT.Shared.Interface.Service/security", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsAuthenticated(ByVal Domain As String, ByVal UserName As String, ByVal Password As String) As Boolean
            Dim results() As Object = Me.Invoke("IsAuthenticated", New Object() {Domain, UserName, Password})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginIsAuthenticated(ByVal Domain As String, ByVal UserName As String, ByVal Password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("IsAuthenticated", New Object() {Domain, UserName, Password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndIsAuthenticated(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Shared.Interface.Service/security/EncryptData", RequestNamespace:="http://tempuri.org/PTT.Shared.Interface.Service/security", ResponseNamespace:="http://tempuri.org/PTT.Shared.Interface.Service/security", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EncryptData(ByVal data As String) As String
            Dim results() As Object = Me.Invoke("EncryptData", New Object() {data})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginEncryptData(ByVal data As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EncryptData", New Object() {data}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndEncryptData(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Shared.Interface.Service/security/DecryptData", RequestNamespace:="http://tempuri.org/PTT.Shared.Interface.Service/security", ResponseNamespace:="http://tempuri.org/PTT.Shared.Interface.Service/security", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DecryptData(ByVal encryptedData As String) As String
            Dim results() As Object = Me.Invoke("DecryptData", New Object() {encryptedData})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginDecryptData(ByVal encryptedData As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DecryptData", New Object() {encryptedData}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDecryptData(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PTT.Shared.Interface.Service/security"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/PTT.Shared.Interface.Service/security", IsNullable:=false)>  _
    Public Class ApplicationError
        Inherits System.Web.Services.Protocols.SoapHeader
        
        '<remarks/>
        Public Message As String
    End Class
End Namespace
