<%
session("user") = ""
response.redirect "default.asp"
Application("txt1")=""
Application("txt2")=""
Application("txt3")=""
Application("txt4")=""
Application("txt5")=""
Application("txt6")=""
Application("txt7")=""
Application("txt8")=""
Application("txt9")=""
Application("txt10")=""
Application("txt11")=""
Application("txt12")=""
Application("txt13")=""
Application("txt14")=""
Application("txt15")=""
%>
<body onload="javascript:window.close()"></body>