                  <select name="enStatus"  onChange="document.form1.dirty.value=1;">
	<option value=""></option>
	<option value="0"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("0"))==0)) {%> selected <%}%>>ประเมินความเป็นไปได้ของโครงการ</option>
	<option value="1"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("1"))==0)) {%> selected <%}%>>จัดทำแผนการพัฒนาธุรกิจ</option>
	<option value="2"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("2"))==0)) {%> selected <%}%>>ดำเนิการยื่นคำร้องจัดตั้งร้านค้าธุรกิจในสถานีบริการ</option>
	<option value="3"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("3"))==0)) {%> selected <%}%>>จัดทำแผนงบประมาณ</option>
	<option value="4"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("4"))==0)) {%> selected <%}%>>จัดทำแผนงานขยายร้านค้าธุรกิจ</option>
	<option value="5"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("5"))==0)) {%> selected <%}%>>จัดทำแผนธุรกิจรายปี</option>
	<option value="6"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("6"))==0)) {%> selected <%}%>>จัดทำแผนปฏิบัติการ</option>
	<option value="7"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("7"))==0)) {%> selected <%}%>>ควบคุมแผนงาน</option>
	<option value="8"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("8"))==0)) {%> selected <%}%>>ประเมินความเป็นไปได้ของที่ตั้ง</option>
	<option value="9"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("9"))==0)) {%> selected <%}%>>กำหนดทางเลือกที่ตั้งที่เป็นไปได้</option>
	<option value="11"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("11"))==0)) {%> selected <%}%>>รวบรวมข้อมูลการออกแบบโครงสร้างสถาปัตยกรรม</option>
	<option value="12"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("12"))==0)) {%> selected <%}%>>ออกแบบโครงสร้างสถาปัตยกรรม</option>
	<option value="13"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("13"))==0)) {%> selected <%}%>>ปรับปรุงโครงสร้างสถาปัตยกรรม</option>
	<option value="14"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("14"))==0)) {%> selected <%}%>>ศึกษาผลกระทบความเป็นไปได้ของที่ตั้ง</option>
	<option value="15"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("15"))==0)) {%> selected <%}%>>พิจารณาที่ตั้ง</option>
	<option value="16"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("16"))==0)) {%> selected <%}%>>เสนอขออนุมัติที่ตั้ง</option>
	<option value="17"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("17"))==0)) {%> selected <%}%>>อนุมัติที่ตั้ง</option>
	<option value="18"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("18"))==0)) {%> selected <%}%>>ประเมินต้นทุนโครงการโดยรายละเอียด</option>
	<option value="19"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("19"))==0)) {%> selected <%}%>>จัดทำแผนการตลาด</option>
	<option value="20"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("20"))==0)) {%> selected <%}%>>ศึกษาความเป็นไปได้ในการลงทุน</option>
	<option value="21"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("21"))==0)) {%> selected <%}%>>เสนอขออนุมัติการลงทุน</option>
	<option value="22"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("22"))==0)) {%> selected <%}%>>ปรับปรุงแผนการลงทุน</option>
	<option value="23"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("23"))==0)) {%> selected <%}%>>ลงนามในสัญญา</option>
	<option value="24"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("24"))==0)) {%> selected <%}%>>ดำเนินการก่อสร้าง</option>
	<option value="25"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("25"))==0)) {%> selected <%}%>>จัดหาอุปกรณ์</option>
	<option value="26"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("26"))==0)) {%> selected <%}%>>ขออนุมัติจัดตั้งร้านค้าจากหน่วยงานรัฐบาล</option>
	<option value="27"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("27"))==0)) {%> selected <%}%>>จัดตั้งร้านค้า</option>
	<option value="28"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("28"))==0)) {%> selected <%}%>>เปิดดำเนินการ</option>
	<option value="29"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("29"))==0)) {%> selected <%}%>>ปิดดำเนินการชั่วคราว</option>
	<option value="30"<%if ((engineeringStatus!=null) && ((engineeringStatus.compareTo("30"))==0)) {%> selected <%}%>>ปิดดำเนินการ</option>
  </select>
