'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace AuditWS

    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="AuditServiceSoap", [Namespace]:="http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit")> _
    Public Class AuditService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Public ApplicationErrorValue As ApplicationError

        Public SecurityPrincipalTypeValue As SecurityPrincipalType

        '<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = System.Configuration.ConfigurationSettings.AppSettings("AuditServiceURL") & ""
            Me.Credentials = System.Net.CredentialCache.DefaultCredentials
            SecurityPrincipalTypeValue = New SecurityPrincipalType
            SecurityPrincipalTypeValue.UserName = HttpContext.Current.Session("USER_NAME")
            SecurityPrincipalTypeValue.Roles = HttpContext.Current.Session("ROLES")
        End Sub

        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ApplicationErrorValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut), _
         System.Web.Services.Protocols.SoapHeaderAttribute("SecurityPrincipalTypeValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit/Insert", RequestNamespace:="http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit", ResponseNamespace:="http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Sub Insert(ByVal transaction As AuditData)
            Me.Invoke("Insert", New Object() {transaction})
        End Sub

        '<remarks/>
        Public Function BeginInsert(ByVal transaction As AuditData, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Insert", New Object() {transaction}, callback, asyncState)
        End Function

        '<remarks/>
        Public Sub EndInsert(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub

        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ApplicationErrorValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut), _
         System.Web.Services.Protocols.SoapHeaderAttribute("SecurityPrincipalTypeValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit/SearchAudit", RequestNamespace:="http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit", ResponseNamespace:="http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchAudit(ByVal TransactionFromDate As Date, ByVal TransactionToDate As Date, ByVal UserId As String, ByVal DeptName As String, ByVal Category As String, ByVal Action As String) As AuditDatas
            Dim results() As Object = Me.Invoke("SearchAudit", New Object() {TransactionFromDate, TransactionToDate, UserId, DeptName, Category, Action})
            Return CType(results(0), AuditDatas)
        End Function

        '<remarks/>
        Public Function BeginSearchAudit(ByVal TransactionFromDate As Date, ByVal TransactionToDate As Date, ByVal UserId As String, ByVal DeptName As String, ByVal Category As String, ByVal Action As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchAudit", New Object() {TransactionFromDate, TransactionToDate, UserId, DeptName, Category, Action}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchAudit(ByVal asyncResult As System.IAsyncResult) As AuditData()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), AuditData())
        End Function
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit", IsNullable:=False)> _
    Public Class ApplicationError
        Inherits System.Web.Services.Protocols.SoapHeader

        '<remarks/>
        Public Message As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit")> _
    Public Class AuditData

        '<remarks/>
        Public TransactionDate As Date

        '<remarks/>
        Public UserId As String

        '<remarks/>
        Public DeptName As String

        '<remarks/>
        Public Category As String

        '<remarks/>
        Public Action As String

        '<remarks/>
        Public MachineName As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/PTT.NGVCIS.BLL.Service/Audit", IsNullable:=False)> _
    Public Class SecurityPrincipalType
        Inherits System.Web.Services.Protocols.SoapHeader

        '<remarks/>
        Public UserName As String

        '<remarks/>
        Public Roles() As String
    End Class
End Namespace
