'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On 

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace CRReportWS

    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="CRReportSoap", [Namespace]:="http://tempuri.org/CSC_IND/BLL/CRReport")> _
    Public Class CRReport
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Public ApplicationErrorValue As ApplicationError

        Public SecurityPrincipalTypeValue As SecurityPrincipalType

        '<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = System.Configuration.ConfigurationSettings.AppSettings("CRReportServiceURL") & ""
            Me.Credentials = System.Net.CredentialCache.DefaultCredentials
            'Me.Credentials = System.Threading.Thread.CurrentThread.CurrentPrincipal.Identity
            'Me.Credentials = New System.Net.NetworkCredential("intersol", "titsxx", "ptt")
            SecurityPrincipalTypeValue = New SecurityPrincipalType
            SecurityPrincipalTypeValue.UserName = HttpContext.Current.Session("USER_NAME")
            SecurityPrincipalTypeValue.Roles = HttpContext.Current.Session("ROLES")
        End Sub

        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityPrincipalTypeValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("ApplicationErrorValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.NGVCIS.BLL.Service/CRReport/GetReportFile", RequestNamespace:="http://tempuri.org/PTT.NGVCIS.BLL.Service/CRReport", ResponseNamespace:="http://tempuri.org/PTT.NGVCIS.BLL.Service/CRReport", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function GetReportFile(ByVal FileName As String, ByVal ParamData As String, ByVal FileType As String, ByVal FSelection As String) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("GetReportFile", New Object() {FileName, ParamData, FileType, FSelection})
            Return CType(results(0), Byte())
        End Function

        '<remarks/>
        Public Function BeginGetReportFile(ByVal FileName As String, ByVal ParamData As String, ByVal FileType As String, ByVal FSelection As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetReportFile", New Object() {FileName, ParamData, FileType, FSelection}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndGetReportFile(ByVal asyncResult As System.IAsyncResult) As Byte()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), Byte())
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityPrincipalTypeValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("ApplicationErrorValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.NGVCIS.BLL.Service/CRReport/ExportReport", RequestNamespace:="http://tempuri.org/PTT.NGVCIS.BLL.Service/CRReport", ResponseNamespace:="http://tempuri.org/PTT.NGVCIS.BLL.Service/CRReport", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ExportReport(ByVal FileName As String, ByVal ParamData As String, ByVal Format As String, ByVal FSelection As String) As String
            Dim results() As Object = Me.Invoke("ExportReport", New Object() {FileName, ParamData, Format, FSelection})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginExportReport(ByVal FileName As String, ByVal ParamData As String, ByVal Format As String, ByVal FSelection As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ExportReport", New Object() {FileName, ParamData, Format, FSelection}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndExportReport(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PTT.NGVCIS.BLL.Service/CRReport"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/PTT.NGVCIS.BLL.Service/CRReport", IsNullable:=False)> _
    Public Class SecurityPrincipalType
        Inherits System.Web.Services.Protocols.SoapHeader

        '<remarks/>
        Public UserName As String

        '<remarks/>
        Public Roles() As String
    End Class

    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PTT.NGVCIS.BLL.Service/CRReport"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/PTT.NGVCIS.BLL.Service/CRReport", IsNullable:=False)> _
    Public Class ApplicationError
        Inherits System.Web.Services.Protocols.SoapHeader

        '<remarks/>
        Public Message As String
    End Class
End Namespace
