'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On 

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace DirectoryWS

    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="DirectorySoap", [Namespace]:="http://tempuri.org/PTT.Directory.BLL.Service/Directory")> _
    Public Class DirectoryService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        '<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Credentials = System.Net.CredentialCache.DefaultCredentials
            Me.Url = System.Configuration.ConfigurationSettings.AppSettings("DirectoryServiceURL") & ""
        End Sub

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/GetDepartmentList", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function GetDepartmentList(ByVal DepartmentCode As String, ByVal DepartmentName As String, ByVal DepartmentABBR As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetDepartmentList", New Object() {DepartmentCode, DepartmentName, DepartmentABBR})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginGetDepartmentList(ByVal DepartmentCode As String, ByVal DepartmentName As String, ByVal DepartmentABBR As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetDepartmentList", New Object() {DepartmentCode, DepartmentName, DepartmentABBR}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndGetDepartmentList(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/GetPositionList", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function GetPositionList(ByVal PositionName As String, ByVal PositionABBR As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetPositionList", New Object() {PositionName, PositionABBR})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginGetPositionList(ByVal PositionName As String, ByVal PositionABBR As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPositionList", New Object() {PositionName, PositionABBR}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndGetPositionList(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchDirectory", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchDirectory(ByVal employeeID As String, ByVal nickname As String, ByVal employeeFName As String, ByVal employeeLName As String, ByVal positionName As String, ByVal positionABBR As String, ByVal departmentCode As String, ByVal departmentABBR As String, ByVal locationId As String, ByVal mobileNo As String, ByVal intPhoneNo As String, ByVal homeNo As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchDirectory", New Object() {employeeID, nickname, employeeFName, employeeLName, positionName, positionABBR, departmentCode, departmentABBR, locationId, mobileNo, intPhoneNo, homeNo})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchDirectory(ByVal employeeID As String, ByVal nickname As String, ByVal employeeFName As String, ByVal employeeLName As String, ByVal positionName As String, ByVal positionABBR As String, ByVal departmentCode As String, ByVal departmentABBR As String, ByVal locationId As String, ByVal mobileNo As String, ByVal intPhoneNo As String, ByVal homeNo As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchDirectory", New Object() {employeeID, nickname, employeeFName, employeeLName, positionName, positionABBR, departmentCode, departmentABBR, locationId, mobileNo, intPhoneNo, homeNo}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchDirectory(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/GetDirectoryInfo", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function GetDirectoryInfo(ByVal employeeId As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetDirectoryInfo", New Object() {employeeId})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginGetDirectoryInfo(ByVal employeeId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetDirectoryInfo", New Object() {employeeId}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndGetDirectoryInfo(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchSite", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchSite(ByVal siteId As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchSite", New Object() {siteId})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchSite(ByVal siteId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchSite", New Object() {siteId}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchSite(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchArea", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchArea(ByVal siteId As String, ByVal areaId As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchArea", New Object() {siteId, areaId})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchArea(ByVal siteId As String, ByVal areaId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchArea", New Object() {siteId, areaId}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchArea(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchLocation", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchLocation(ByVal locationId As String, ByVal siteId As String, ByVal areaId As String, ByVal floor As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchLocation", New Object() {locationId, siteId, areaId, floor})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchLocation(ByVal locationId As String, ByVal siteId As String, ByVal areaId As String, ByVal floor As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchLocation", New Object() {locationId, siteId, areaId, floor}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchLocation(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchDepartmentGroup", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchDepartmentGroup(ByVal siteCode As String, ByVal areaCode As String, ByVal floor As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchDepartmentGroup", New Object() {siteCode, areaCode, floor})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchDepartmentGroup(ByVal siteCode As String, ByVal areaCode As String, ByVal floor As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchDepartmentGroup", New Object() {siteCode, areaCode, floor}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchDepartmentGroup(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchPersonByLocation", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchPersonByLocation(ByVal locationId As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchPersonByLocation", New Object() {locationId})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchPersonByLocation(ByVal locationId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchPersonByLocation", New Object() {locationId}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchPersonByLocation(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchFWAssign", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchFWAssign(ByVal locationId As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchFWAssign", New Object() {locationId})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchFWAssign(ByVal locationId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchFWAssign", New Object() {locationId}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchFWAssign(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchContractorByLocation" & _
"", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchContractorByLocation(ByVal locationId As String, ByVal personTypeCode As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchContractorByLocation", New Object() {locationId, personTypeCode})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchContractorByLocation(ByVal locationId As String, ByVal personTypeCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchContractorByLocation", New Object() {locationId, personTypeCode}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchContractorByLocation(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchCommittee", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchCommittee(ByVal code As String, ByVal groupCode As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchCommittee", New Object() {code, groupCode})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchCommittee(ByVal code As String, ByVal groupCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchCommittee", New Object() {code, groupCode}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchCommittee(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/GetLocation", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function GetLocation() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetLocation", New Object(-1) {})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginGetLocation(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetLocation", New Object(-1) {}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndGetLocation(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchEmployeeNameByID", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchEmployeeNameByID(ByVal employeeId As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchEmployeeNameByID", New Object() {employeeId})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchEmployeeNameByID(ByVal employeeId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchEmployeeNameByID", New Object() {employeeId}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchEmployeeNameByID(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PTT.Directory.BLL.Service/Directory/SearchCommitteeGroup", RequestNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", ResponseNamespace:="http://tempuri.org/PTT.Directory.BLL.Service/Directory", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function SearchCommitteeGroup(ByVal groupCode As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SearchCommitteeGroup", New Object() {groupCode})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '<remarks/>
        Public Function BeginSearchCommitteeGroup(ByVal groupCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchCommitteeGroup", New Object() {groupCode}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndSearchCommitteeGroup(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function
    End Class
End Namespace
