<%@ Language=VBScript %>
<%
	Option Explicit
	Response.Expires = 0
%>
<html>
<head>
	<meta http-equiv="Content-Language" content="th">
	<meta http-equiv="Content-Type" content="text/html; charset=windows-874">
	<link href="../INCLUDE/StyleSheet.css" rel="stylesheet" type="text/css">
</head>
<body bgcolor="#E8F8FF">
  <form name="form1" method="post" action="">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        
      <td height="10"><img src="../images/blank.gif" width="1" height="1"></td>
      </tr>
      <tr>
        <td><table width="85%" border="0" align="center" cellpadding="0" cellspacing="0" bordercolor="#111111" style="border-collapse: collapse">
            <tr> 
              <td width="100%"><b><a style="text-decoration: none" href="provider.asp"><font color="#4B0097">ข้อมูลกลุ่มบริษัทสื่อสาร</font></a></b></td>
            </tr>
          </table></td>
      </tr>
      <tr>
        <td><table width="69%" border="0" align="center" cellpadding="0" cellspacing="0" bordercolor="#111111" style="border-collapse: collapse">
            <tr> 
              <td width="13%"><a target="_blank" href="http://172.20.31.37/cmo/clip/login.asp"><img border="0" src="../images/ttt.gif" width="61" height="29"></a></td>
              <td width="87%"><font size="2" color="#4B0097">&lt;--ข้อมูล TT&amp;T 
                คลิกที่นี่</font></td>
            </tr>
          </table></td>
      </tr>
      <tr>
        <td><table width="544" border="3" align="center" cellpadding="0" cellspacing="3" bordercolor="#FFFFFF" style="border-collapse: collapse">
            <tr> 
              <td width="278" align="center" ><font color="#4B0097" size="2"><b>ชื่อบริษัทผู้ให้บริการ</b></font></td>
              <td width="78" align="center"><font color="#4B0097" size="2"><b>Hyperlink</b></font></td>
              <td align="center" width="79"><font color="#4B0097" size="2"><b>ประเภทบริการ</b></font></td>
            </tr>
            <tr> 
              <td align="center"><font size="2" color="#4B0097">TOT Corporation 
                Public Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.tot.co.th"><img border="0" src="../images/tot3.gif" width="61" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097">โทรศัพท์พื้นฐาน</font></td>
            </tr>
            <tr> 
              <td align="center"><font color="#4B0097" size="2">Telecomasia Corporation 
                Public Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.telecomasia.co.th"><img border="0" src="../images/ta.gif" width="61" height="39"></a></td>
              <td align="center"><font size="2" color="#4B0097">โทรศัพท์พื้นฐาน</font></td>
            </tr>
            <tr> 
              <td align="center"><font color="#4B0097" size="2">&nbsp;Advance 
                Info Service Public Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.ais.co.th"><img border="0" src="../images/ais.gif" width="64" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097" >Mobile</font></td>
            </tr>
            <tr> 
              <td align="center"><font size="2" color="#4B0097">Total Access Communication 
                Public Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.dtac.co.th"><img border="0" src="../images/dtac.gif" width="61" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097" >Mobile</font></td>
            </tr>
            <tr> 
              <td align="center"><font size="2" color="#4B0097">&nbsp;TA Orange 
                Public Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.orange.co.th/"><img border="0" src="../images/logo_orange.gif" width="40" height="40"></a></td>
              <td align="center"><font size="2" color="#4B0097">Mobile</font></td>
            </tr>
            <tr> 
              <td align="center"><font size="2" color="#4B0097">Hutchison Cat 
                Wireless Multimedia Ltd.</font></td>
              <td align="center"><a target="_blank" href="http://www.hutch.co.th"><img border="0" src="../images/hutch3.gif" width="61" height="39"></a></td>
              <td align="center"><font size="2" color="#4B0097" >Mobile</font></td>
            </tr>
            <tr> 
              <td align="center"><font size="2" color="#4B0097">CAT Telecom Public 
                Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.cat.or.th"><img border="0" src="../images/cat2.gif" width="61" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097" >สื่อสารข้อมูล</font></td>
            </tr>
            <tr> 
              <td align="center"><font size="2" color="#4B0097">Acumen Public 
                Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.acumen.co.th"><img border="0" src="../images/acumen.gif" width="61" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097">สื่อสารข้อมูล</font></td>
            </tr>
            <tr> 
              <td align="center"><font color="#4B0097" size="2">&nbsp;Advanced 
                Datanetwork Communications Co., Ltd.</font></td>
              <td align="center"><a target="_blank" href="http://www.adc.co.th"><img border="0" src="../images/adc.gif" width="61" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097" >สื่อสารข้อมูล</font></td>
            </tr>
            <tr> 
              <td align="center"><font size="2" color="#4B0097" >Jasmine&nbsp;International 
                Public Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.jasmine.com"><img border="0" src="../images/jasmin.gif" width="51" height="39"></a></td>
              <td align="center"><font size="2" color="#4B0097">สื่อสารข้อมูล</font></td>
            </tr>
            <tr> 
              <td align="center"><font size="2" color="#4B0097" >KSC Commercial 
                Internet Public Company Limited.</font></td>
              <td align="center"><a href="http://www.ksc.net.th/" target="_blank"><img border="0" src="../images/ksc.gif" width="61" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097">สื่อสารข้อมูล</font></td>
            </tr>
            <tr> 
              <td align="center"><font size="2" color="#4B0097">&nbsp;Samart Corporation.</font></td>
              <td align="center"><a target="_blank" href="http://www.samart.co.th"><img border="0" src="../images/samart.gif" width="61" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097" >สื่อสารข้อมูล</font></td>
            </tr>
            <tr> 
              <td align="center"><font size="2" color="#4B0097" >Samart Comtech 
                Public Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.samart.co.th"><img border="0" src="../images/samart_comtech.gif" width="61" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097" >สื่อสารข้อมูล</font></td>
            </tr>
            <tr> 
              <td align="center"><font color="#4B0097" size="2">Shin Corporation 
                Public Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.shin.co.th"><img border="0" src="../images/shin.gif" width="61" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097" >สื่อสารข้อมูล</font></td>
            </tr>
            <tr> 
              <td align="center"><font color="#4B0097" size="2">Shin Satellite 
                Public Company Limited.</font></td>
              <td align="center"><a target="_blank" href="http://www.thaicom.co.th"><img border="0" src="../images/thaicom.gif" width="61" height="39"></a></td>
              <td align="center"><font size="2" color="#4B0097" >สื่อสารข้อมูล</font></td>
            </tr>
            <tr> 
              <td align="center"><font color="#4B0097" size="2">United Communication 
                Industry Public Co.,Ltd.</font></td>
              <td align="center"><a target="_blank" href="http://www.ucom.co.th"><img border="0" src="../images/ucom.gif" width="61" height="29"></a></td>
              <td align="center"><font size="2" color="#4B0097" >สื่อสารข้อมูล</font></td>
            </tr>
          </table></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table>
  </form>
  </body>
</html>
